/**
 * Common vehicle makes/models for Malawi + South Africa markets.
 * Japanese imports dominate Malawi; SA bakkie/city hatchbacks and
 * growing Chinese brands are included for cross-border imports.
 */

export const OTHER_VEHICLE_VALUE = '__other__';

export const VEHICLE_MAKES = [
  'Toyota',
  'Nissan',
  'Honda',
  'Mazda',
  'Mitsubishi',
  'Suzuki',
  'Isuzu',
  'Ford',
  'Volkswagen',
  'Hyundai',
  'Kia',
  'Subaru',
  'Renault',
  'Peugeot',
  'Chevrolet',
  'GWM',
  'Haval',
  'Chery',
  'Jetour',
  'Omoda',
  'Mahindra',
  'Tata',
  'Mercedes-Benz',
  'BMW',
  'Audi',
  'Land Rover',
  'Lexus',
] as const;

export type VehicleMakeOption = (typeof VEHICLE_MAKES)[number];

export const VEHICLE_MODELS_BY_MAKE: Record<VehicleMakeOption, string[]> = {
  Toyota: [
    'Vitz',
    'Passo',
    'Starlet',
    'Corolla',
    'Corolla Cross',
    'Axio',
    'Premio',
    'Allion',
    'Camry',
    'Wish',
    'Noah',
    'Voxy',
    'Probox',
    'Succeed',
    'Urban Cruiser',
    'RAV4',
    'Harrier',
    'Fortuner',
    'Hilux',
    'Land Cruiser',
    'Land Cruiser 70',
    'Prado',
    '4Runner',
    'Quantum',
    'HiAce',
  ],
  Nissan: [
    'March',
    'Note',
    'Tiida',
    'Latio',
    'Almera',
    'Sunny',
    'AD Van',
    'Wingroad',
    'Dualis',
    'Qashqai',
    'X-Trail',
    'Navara',
    'NP200',
    'NP300',
    'Hardbody',
    'Caravan',
    'Patrol',
  ],
  Honda: ['Fit', 'Jazz', 'Insight', 'Civic', 'City', 'Accord', 'CR-V', 'HR-V', 'Stream', 'Freed', 'Stepwgn'],
  Mazda: ['Demio', 'Mazda2', 'Mazda3', 'Axela', 'Atenza', 'Mazda6', 'CX-3', 'CX-5', 'CX-30', 'Premacy', 'BT-50'],
  Mitsubishi: [
    'Mirage',
    'Lancer',
    'Attrage',
    'ASX',
    'RVR',
    'Outlander',
    'Eclipse Cross',
    'Pajero',
    'Pajero Sport',
    'Triton',
    'L200',
    'Xpander',
  ],
  Suzuki: [
    'Alto',
    'Celerio',
    'Swift',
    'Baleno',
    'Dzire',
    'Vitara',
    'Grand Vitara',
    'Jimny',
    'Ertiga',
    'Fronx',
    'S-Presso',
    'Every',
    'Carry',
  ],
  Isuzu: ['D-Max', 'KB', 'MU-X', 'Trooper', 'Elf', 'NPR', 'FRR'],
  Ford: ['Fiesta', 'Focus', 'EcoSport', 'Everest', 'Ranger', 'Territory', 'Transit', 'Figo'],
  Volkswagen: [
    'Polo',
    'Polo Vivo',
    'Golf',
    'Jetta',
    'Passat',
    'T-Cross',
    'Tiguan',
    'Touareg',
    'Amarok',
    'Caddy',
    'Transporter',
  ],
  Hyundai: [
    'i10',
    'Grand i10',
    'i20',
    'Accent',
    'Elantra',
    'Creta',
    'Venue',
    'Tucson',
    'Santa Fe',
    'H-1',
    'H100',
  ],
  Kia: ['Picanto', 'Rio', 'Sonet', 'Seltos', 'Sportage', 'Sorento', 'Cerato', 'Carnival', 'K2700'],
  Subaru: ['Impreza', 'Legacy', 'Outback', 'Forester', 'XV', 'Crosstrek', 'WRX'],
  Renault: ['Kwid', 'Sandero', 'Logan', 'Duster', 'Triber', 'Kiger', 'Captur', 'Megane'],
  Peugeot: ['208', '301', '2008', '3008', '5008', 'Partner', 'Landtrek'],
  Chevrolet: ['Spark', 'Aveo', 'Cruze', 'Captiva', 'Trailblazer', 'Utility', 'Optra'],
  GWM: ['P-Series', 'Poer', 'Steed', 'Cannon', 'Tank 300', 'Ora'],
  Haval: ['Jolion', 'H6', 'H6 GT', 'H9', 'H2'],
  Chery: ['Tiggo 4', 'Tiggo 4 Pro', 'Tiggo 7', 'Tiggo 7 Pro', 'Tiggo 8', 'Tiggo 8 Pro', 'QQ'],
  Jetour: ['X70', 'X70 Plus', 'Dashing', 'T1', 'T2'],
  Omoda: ['C5', 'C7', 'E5'],
  Mahindra: ['Bolero', 'Scorpio', 'Scorpio Pik Up', 'XUV300', 'XUV 3XO', 'XUV500', 'XUV700', 'Pik Up'],
  Tata: ['Indica', 'Tiago', 'Punch', 'Nexon', 'Xenon', 'Yodha', 'Ace', 'Super Ace'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'GLA', 'GLC', 'GLE', 'Sprinter', 'Vito'],
  BMW: ['1 Series', '2 Series', '3 Series', '5 Series', 'X1', 'X3', 'X5', 'X6'],
  Audi: ['A3', 'A4', 'A6', 'Q2', 'Q3', 'Q5', 'Q7'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover Evoque', 'Range Rover Sport'],
  Lexus: ['CT', 'IS', 'ES', 'RX', 'NX', 'LX', 'UX'],
};

export const getModelsForMake = (make: string): string[] => {
  if (!make || make === OTHER_VEHICLE_VALUE) return [];
  return VEHICLE_MODELS_BY_MAKE[make as VehicleMakeOption] ?? [];
};
